// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Method_Enum

/** 请求方法 */
typedef GPB_ENUM(Method_Enum) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Method_Enum_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Method_Enum_Get = 0,
  Method_Enum_Post = 1,
  Method_Enum_Put = 2,
  Method_Enum_Patch = 3,
  Method_Enum_Delete = 4,
};

GPBEnumDescriptor *Method_Enum_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Method_Enum_IsValidValue(int32_t value);

#pragma mark - Enum Response_Status

typedef GPB_ENUM(Response_Status) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Response_Status_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Response_Status_Undefined = 0,
  Response_Status_StatusOk = 200,
  Response_Status_StatusCreated = 201,
  Response_Status_StatusNoContent = 204,
  Response_Status_StatusBadRequest = 400,
  Response_Status_StatusUnauthorized = 401,
  Response_Status_StatusForbidden = 403,
  Response_Status_StatusNotFound = 404,
  Response_Status_StatusMethodNotAllowed = 405,
  Response_Status_StatusInternalServererror = 500,
  Response_Status_StatusNotImplemented = 501,
  Response_Status_StatusBadGateway = 502,
  Response_Status_StatusServiceUnavailable = 503,
  Response_Status_StatusGatewayTimeout = 504,
};

GPBEnumDescriptor *Response_Status_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Response_Status_IsValidValue(int32_t value);

#pragma mark - ContractRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ContractRoot : GPBRootObject
@end

#pragma mark - Event

typedef GPB_ENUM(Event_FieldNumber) {
  Event_FieldNumber_Id_p = 1,
  Event_FieldNumber_Endpoint = 2,
  Event_FieldNumber_Action = 3,
  Event_FieldNumber_SubAction = 4,
  Event_FieldNumber_When = 5,
  Event_FieldNumber_Param = 6,
};

/**
 * 事件
 **/
@interface Event : GPBMessage

/** 事件 id，唯一标识每个端发出的数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 标识发送事件的端，规则：“(mobile|robot|cloud:package_name)” */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endpoint;

/** 事件行为 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *action;

/** 事件子行为 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subAction;

/** 事件发生时间 */
@property(nonatomic, readwrite) int64_t when;

/** 事件携带的参数 */
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_Id_p = 1,
  Request_FieldNumber_Endpoint = 2,
  Request_FieldNumber_Uri = 3,
  Request_FieldNumber_Method = 4,
  Request_FieldNumber_When = 5,
  Request_FieldNumber_Param = 6,
};

/**
 * 请求
 **/
@interface Request : GPBMessage

/** 请求 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 标识发送请求的端，规则：“(mobile|robot|cloud:package_name)” */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endpoint;

/** 请求资源标识符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

/** 请求方法 */
@property(nonatomic, readwrite) Method_Enum method;

/** 请求时间 */
@property(nonatomic, readwrite) int64_t when;

/** 请求参数 */
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@end

/**
 * Fetches the raw value of a @c Request's @c method property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Request_Method_RawValue(Request *message);
/**
 * Sets the raw value of an @c Request's @c method property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequest_Method_RawValue(Request *message, int32_t value);

#pragma mark - Response

typedef GPB_ENUM(Response_FieldNumber) {
  Response_FieldNumber_Status = 1,
  Response_FieldNumber_Id_p = 2,
  Response_FieldNumber_ReqId = 3,
  Response_FieldNumber_Endpoint = 4,
  Response_FieldNumber_ReqEndpoint = 5,
  Response_FieldNumber_Uri = 6,
  Response_FieldNumber_Method = 7,
  Response_FieldNumber_When = 8,
  Response_FieldNumber_Param = 9,
};

/**
 * 响应
 **/
@interface Response : GPBMessage

/** 响应的状态码 */
@property(nonatomic, readwrite) Response_Status status;

/** 响应 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 响应的请求的 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reqId;

/** 标识发送请求的端，规则：“(mobile|robot|cloud:package_name)” */
@property(nonatomic, readwrite, copy, null_resettable) NSString *endpoint;

/** 响应的请求的端 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reqEndpoint;

/** 响应的请求的资源标识符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

/** 响应的请求的方法 */
@property(nonatomic, readwrite) Method_Enum method;

/** 响应时间 */
@property(nonatomic, readwrite) int64_t when;

/** 请求参数 */
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *param;
/** Test to see if @c param has been set. */
@property(nonatomic, readwrite) BOOL hasParam;

@end

/**
 * Fetches the raw value of a @c Response's @c status property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Response_Status_RawValue(Response *message);
/**
 * Sets the raw value of an @c Response's @c status property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponse_Status_RawValue(Response *message, int32_t value);

/**
 * Fetches the raw value of a @c Response's @c method property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Response_Method_RawValue(Response *message);
/**
 * Sets the raw value of an @c Response's @c method property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponse_Method_RawValue(Response *message, int32_t value);

#pragma mark - Error

typedef GPB_ENUM(Error_FieldNumber) {
  Error_FieldNumber_Code = 1,
  Error_FieldNumber_Message = 2,
  Error_FieldNumber_Detail = 3,
};

/**
 * 错误参数，出错情况下将该类型的实例填充到 param 字段
 **/
@interface Error : GPBMessage

/** 错误码 */
@property(nonatomic, readwrite) int32_t code;

/** 错误消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** 错误详情 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *detail;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
