// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: params.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ParamsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ParamsRoot : GPBRootObject
@end

#pragma mark - DiscoverParam

typedef GPB_ENUM(DiscoverParam_FieldNumber) {
  DiscoverParam_FieldNumber_DiscoverHost = 1,
  DiscoverParam_FieldNumber_DiscoverPort = 2,
  DiscoverParam_FieldNumber_Broadcast = 3,
};

@interface DiscoverParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *discoverHost;

@property(nonatomic, readwrite) int32_t discoverPort;

@property(nonatomic, readwrite, copy, null_resettable) NSString *broadcast;

@end

#pragma mark - DiscoveredParam

typedef GPB_ENUM(DiscoveredParam_FieldNumber) {
  DiscoveredParam_FieldNumber_DiscoverEventId = 1,
  DiscoveredParam_FieldNumber_PacketHubHost = 2,
  DiscoveredParam_FieldNumber_PacketHubPort = 3,
  DiscoveredParam_FieldNumber_PacketHubName = 4,
};

@interface DiscoveredParam : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *discoverEventId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *packetHubHost;

@property(nonatomic, readwrite) int32_t packetHubPort;

@property(nonatomic, readwrite, copy, null_resettable) NSString *packetHubName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
