// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync_params.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MetaData;
@class ModifyData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SyncParamsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SyncParamsRoot : GPBRootObject
@end

#pragma mark - AddRequest

typedef GPB_ENUM(AddRequest_FieldNumber) {
  AddRequest_FieldNumber_SeqId = 1,
  AddRequest_FieldNumber_Data_p = 2,
};

@interface AddRequest : GPBMessage

@property(nonatomic, readwrite) int64_t seqId;

@property(nonatomic, readwrite, strong, null_resettable) MetaData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - PullRequest

typedef GPB_ENUM(PullRequest_FieldNumber) {
  PullRequest_FieldNumber_SeqId = 1,
  PullRequest_FieldNumber_LastServerUuid = 2,
  PullRequest_FieldNumber_ClientDataVersion = 3,
  PullRequest_FieldNumber_Context = 4,
  PullRequest_FieldNumber_PageSize = 5,
};

@interface PullRequest : GPBMessage

@property(nonatomic, readwrite) int64_t seqId;

/** last device id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastServerUuid;

@property(nonatomic, readwrite) int64_t clientDataVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSData *context;

@property(nonatomic, readwrite) int32_t pageSize;

@end

#pragma mark - PullResponse

typedef GPB_ENUM(PullResponse_FieldNumber) {
  PullResponse_FieldNumber_SeqId = 1,
  PullResponse_FieldNumber_ServerUuid = 2,
  PullResponse_FieldNumber_ServerDataVersion = 3,
  PullResponse_FieldNumber_Mode = 4,
  PullResponse_FieldNumber_DataArray = 5,
  PullResponse_FieldNumber_Context = 6,
  PullResponse_FieldNumber_TotalSize = 7,
  PullResponse_FieldNumber_HasNext = 8,
  PullResponse_FieldNumber_Code = 9,
};

@interface PullResponse : GPBMessage

@property(nonatomic, readwrite) int64_t seqId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverUuid;

@property(nonatomic, readwrite) int64_t serverDataVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MetaData*> *dataArray;
/** The number of items in @c dataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dataArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSData *context;

@property(nonatomic, readwrite) int32_t totalSize;

@property(nonatomic, readwrite) BOOL hasNext;

@property(nonatomic, readwrite) int32_t code;

@end

#pragma mark - PushRequest

typedef GPB_ENUM(PushRequest_FieldNumber) {
  PushRequest_FieldNumber_SeqId = 1,
  PushRequest_FieldNumber_OperateArray = 2,
};

@interface PushRequest : GPBMessage

@property(nonatomic, readwrite) int64_t seqId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ModifyData*> *operateArray;
/** The number of items in @c operateArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger operateArray_Count;

@end

#pragma mark - PushResponse

typedef GPB_ENUM(PushResponse_FieldNumber) {
  PushResponse_FieldNumber_SeqId = 1,
  PushResponse_FieldNumber_Code = 2,
};

@interface PushResponse : GPBMessage

@property(nonatomic, readwrite) int64_t seqId;

@property(nonatomic, readwrite) int32_t code;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
