// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync_files.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SyncFilesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SyncFilesRoot : GPBRootObject
@end

#pragma mark - MetaData

typedef GPB_ENUM(MetaData_FieldNumber) {
  MetaData_FieldNumber_Name = 1,
  MetaData_FieldNumber_Path = 2,
  MetaData_FieldNumber_Thumbnail = 3,
  MetaData_FieldNumber_Preview = 4,
  MetaData_FieldNumber_TagArray = 5,
  MetaData_FieldNumber_Type = 6,
  MetaData_FieldNumber_LocationArray = 7,
  MetaData_FieldNumber_CreateTime = 8,
  MetaData_FieldNumber_UpdateTime = 9,
  MetaData_FieldNumber_ResolutionArray = 10,
  MetaData_FieldNumber_Size = 11,
  MetaData_FieldNumber_Action = 12,
  MetaData_FieldNumber_Duration = 13,
  MetaData_FieldNumber_Any = 14,
};

@interface MetaData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbnail;

@property(nonatomic, readwrite, copy, null_resettable) NSString *preview;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *tagArray;
/** The number of items in @c tagArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tagArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

@property(nonatomic, readwrite, strong, null_resettable) GPBDoubleArray *locationArray;
/** The number of items in @c locationArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger locationArray_Count;

@property(nonatomic, readwrite) int64_t createTime;

@property(nonatomic, readwrite) int64_t updateTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *resolutionArray;
/** The number of items in @c resolutionArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resolutionArray_Count;

@property(nonatomic, readwrite) int64_t size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *action;

@property(nonatomic, readwrite) int64_t duration;

@property(nonatomic, readwrite, strong, null_resettable) GPBAny *any;
/** Test to see if @c any has been set. */
@property(nonatomic, readwrite) BOOL hasAny;

@end

#pragma mark - ModifyData

typedef GPB_ENUM(ModifyData_FieldNumber) {
  ModifyData_FieldNumber_Name = 1,
  ModifyData_FieldNumber_Path = 2,
  ModifyData_FieldNumber_NewName = 3,
  ModifyData_FieldNumber_NewPath = 4,
  ModifyData_FieldNumber_Action = 5,
  ModifyData_FieldNumber_CreateTime = 6,
  ModifyData_FieldNumber_UpdateTime = 7,
  ModifyData_FieldNumber_Any = 8,
};

@interface ModifyData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

/** only used in rename action */
@property(nonatomic, readwrite, copy, null_resettable) NSString *newName NS_RETURNS_NOT_RETAINED;

@property(nonatomic, readwrite, copy, null_resettable) NSString *newPath NS_RETURNS_NOT_RETAINED;

@property(nonatomic, readwrite, copy, null_resettable) NSString *action;

@property(nonatomic, readwrite) int64_t createTime;

@property(nonatomic, readwrite) int64_t updateTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBAny *any;
/** Test to see if @c any has been set. */
@property(nonatomic, readwrite) BOOL hasAny;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
